### PR TITLE
Migrate Elyra extensions to support JupyterLab 4.2.5

### PR DESCRIPTION
**Pull request by paulovmr**
### What changes were proposed in this pull request?

* Migrated pipeline-editor, python-editor, metadata, code-snippet, script-debugger and theme extensions to work on JupyterLab 4.2.5.
* Stabilized automated tests
* Improved the CI workflow
* Fixed several UI components that broke after the migration.

There is a need for more changes to merge this PR, because a few extensions, such as scala-editor and r-editor, and the support for Airflow were not changed or tested.

### How was this pull request tested?

Building and running on JupyterLab 4.2.5.
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by lresende** [comment]
@paulovmr Any specific requirements to build? Tried using `make clean install` with yarn 3.5 and 4.5.1 and got similar results
```
 Lerna (powered by Nx)   Running target build for 13 projects failed

Tasks not run because their dependencies failed or --nx-bail=true:

- @elyra/code-snippet-extension:build
- @elyra/metadata-extension:build
- @elyra/pipeline-editor-extension:build

Failed tasks:

- @elyra/scala-editor-extension:build
- @elyra/r-editor-extension:build

make: *** [build-ui] Error 1
```

**Comment by caponetto** [comment]
Hi @lresende. I believe this PR is not in a state to be run as-is yet. As @paulovmr mentioned, there is still work to be done. For instance, we haven't touched the `scala-editor`, `r-editor`, and `code-viewer` extensions, as we are not using them on our fork. The migration process to JL4 that we've done to the other extensions still needs to be applied to these extensions.

**Comment by caponetto** [comment]
@lresende I've collected the diff between our fork and this PR. There are some missing mandatory changes, some nice-to-have bugs that we've fixed, and some changes that we have done to personalize our fork. I tried to discard the personalized stuff, skipped the build of the extensions we haven't touched yet, and ended up having [this patch](https://gist.github.com/caponetto/e462a4f2bd24225a0fe619157a420083). If I'm not missing anything, you can apply this patch on top of this PR to build and run the extensions.

**Comment by lresende** [comment]
Thank you @caponetto feel free to continue to update this PR with the proposed patch.

**Comment by caponetto** [comment]
@lresende could you please try to build it again? I've added the missing changes in my last commit.

**Comment by shalberd** [comment]
@caponetto interesting patch, yeah, odh-elyra vs elyra.

About bootstrapper.py:

Check out the changes in elyra main that have been merged:

https://github.com/elyra-ai/elyra/pull/3243

https://github.com/elyra-ai/elyra/pull/3227

https://elyra.readthedocs.io/en/latest/user_guide/env-variables-file-based-nodes.html

Those are probably not build-relevant, however, the making of kfp libraries optional during build is:

https://github.com/elyra-ai/elyra/commit/7cc3270098c0a21adc37f277be44549998bd731c

@lresende the latest documentation changes have not appeared yet in latest readthedocs. Is there an additional step needed to publish to readthedocs?

**Comment by Zsailer** [comment]
Hi all, I pulled this down locally and tested it out. Looking good so far. Great work @paulovmr and @caponetto. 

One thing to keep in mind when building... using the latest versions of yarn (>=4) will cause the build to fail.

I'm noticed that Elyra's developer docs recommend installing and using yarn directly. However, JupyterLab ships its own pinned version of yarn, called `jlpm`. If I recall correctly, it's recommended that extensions use `jlpm` over `yarn` directly to guard against these kind of build issues. 

It might be worth replacing references to yarn with `jlpm` in the docs and not necessary require folks to install yarn directly.

**Comment by lresende** [comment]
Thanks @Zsailer @paulovmr and @caponetto , I will look into this later today or over the weekend. Do you want to mark this ready for review and I can merge into the main pr.

**Review by lresende — APPROVED** [review]
LGTM, please change from draft so I can merge..

**Pull request merged**
